### PR TITLE
Chakra UI, Absolute Imports, Firestore.

### PR DESCRIPTION
**Pull request by leerob**
Contents from the second stream. 

- Explain the design process I take
- Talk about best practices with Next.js data fetching
- Save user data to Firestore
- Set up Chakra UI
- Add absolute imports and aliases

### CODE REVIEW

**Comment by leerob** [comment]
#### 📝Changed routes:


| [**/**](https://fastfeedback-git-stream-2.leerob1.now.sh/) |
|:-:|
|<a href="https://fastfeedback-git-stream-2.leerob1.now.sh/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/jhLpf_8iqG5AxS_d4C2airuzxfc_.png">(view full size)</a> |







Commit fc6ecb93cfa4582e80c45aa4c1e9a8a5de77c87b (https://fastfeedback-git-stream-2.leerob1.now.sh).

**Comment by leerob** [comment]
For anyone lurking who wants to see the second stream... message me 😄

**Comment by jletey** [comment]
> message me 😄

@leerob Where's the best place to do that? Twitter?

**Comment by leerob** [comment]
@jletey Yeah, that will work!

**Comment by pabloobandodev** [comment]
Hey there 👋 

Guys who are doing the course of React 2025 🎉 

If when you do the merge of these changes to your master branch, receive this error deploy

Screen Shot 2020-09-09 at 17 57 13

Is because you forget to add your Environment Variables in your project at vercel

To fix it, you must to go to your project at Vercel, in settings, environment variables, and add the variables that you have in your .env.local file 😄


Screen Shot 2020-09-09 at 18 01 26

**Comment by leerob** [comment]
Thanks for adding that @pabloobandodev ❤️

**Comment by henriquestiagoo** [comment]
Hi!

You rock @leerob. 
Thanks for sharing your knowledge 😀

**Pull request merged**
